spring.datasource.url: jdbc:h2:file:./camunda-h2-database
camunda.bpm.admin-user:
  id: admin
  password: admin
microservices:
  api-gateway:
    url: "http://localhost:8093/"
camunda:
  bpm:
    auto-deployment-enabled: false
